#!/usr/bin/env python3
import argparse
import csv
import json
import sys
from collections import Counter
from pathlib import Path


def main():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")

    parser = argparse.ArgumentParser(description="Apply model calibration suggestions to a draft tag artifact.")
    parser.add_argument("--workspace", default=".", help="Project workspace root.")
    parser.add_argument("--tags", required=True, help="Source all_question_tags.json generated by local rules.")
    parser.add_argument("--suggestions", required=True, help="JSONL calibration suggestions.")
    parser.add_argument("--output", required=True, help="Output directory for calibrated artifacts.")
    parser.add_argument("--student-records", help="Optional student_exam_records.jsonl used for a recommendation smoke output.")
    parser.add_argument("--student-id", default=None, help="Optional student id; defaults to the first record when --student-records is supplied.")
    parser.add_argument("--format", choices=["text", "json"], default="text", help="Summary output format.")
    args = parser.parse_args()

    workspace = Path(args.workspace).resolve()
    scripts_dir = Path(__file__).resolve().parent
    if str(scripts_dir) not in sys.path:
        sys.path.insert(0, str(scripts_dir))

    from tagging import (
        build_indices,
        calculate_student_mastery,
        recommend_for_student,
        _flat_question_tags,
        _question_summary,
        _read_jsonl,
        _write_json,
        _write_jsonl,
        _write_review_csv,
    )

    tags_path = _resolve_path(workspace, args.tags)
    suggestions_path = _resolve_path(workspace, args.suggestions)
    output = Path(args.output).resolve()

    tagged_questions = json.loads(tags_path.read_text(encoding="utf-8"))
    suggestions = _read_suggestions(suggestions_path)
    applied_rows = _apply_suggestions(tagged_questions, suggestions)

    indices = build_indices(tagged_questions)

    _write_json(output / "tags" / "all_question_tags.calibrated.json", tagged_questions)
    _write_jsonl(output / "tags" / "question_tags.calibrated.jsonl", _flat_question_tags(tagged_questions))
    _write_json(output / "index" / "knowledge_index.json", indices["knowledge_index"])
    _write_json(output / "index" / "difficulty_index.json", indices["difficulty_index"])
    _write_json(output / "index" / "ability_index.json", indices["ability_index"])
    if args.student_records:
        records_path = _resolve_path(workspace, args.student_records)
        records = _read_jsonl(records_path)
        if not records:
            raise SystemExit("Student records file is empty")
        student_id = args.student_id or str(records[0].get("student_id") or "").strip()
        if not student_id:
            raise SystemExit("Student records do not contain a usable student_id")
        tags_by_question = {item["question_id"]: item["tags"] for item in tagged_questions}
        mastery = calculate_student_mastery(records, tags_by_question)
        question_bank = [_question_summary(item) for item in tagged_questions]
        recommendations = recommend_for_student(student_id, records, question_bank, tags_by_question, mastery, top_n=5)
        _write_jsonl(output / "student" / "student_mastery.jsonl", mastery)
        _write_json(
            output / "recommendations" / "sample_recommendations.json",
            {"student_id": student_id, "recommendations": recommendations},
        )
    _write_review_csv(output / "review" / "all_tag_review.calibrated.csv", tagged_questions)
    _write_change_report(output / "calibration_change_report.csv", applied_rows)

    summary = _summary(tagged_questions, suggestions, applied_rows, output, tags_path, suggestions_path)
    (output / "calibration_summary.md").write_text(_summary_markdown(summary), encoding="utf-8")

    if args.format == "json":
        print(json.dumps(summary, ensure_ascii=False, indent=2))
    else:
        for key, value in summary.items():
            print(f"{key}: {value}")


def _resolve_path(workspace, raw):
    path = Path(raw)
    if not path.is_absolute():
        path = workspace / path
    if not path.exists():
        raise SystemExit(f"File not found: {path}")
    return path.resolve()


def _read_suggestions(path):
    suggestions = {}
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            item = json.loads(line)
            question_id = item.get("question_id")
            if question_id:
                suggestions[question_id] = item
    return suggestions


def _apply_suggestions(tagged_questions, suggestions):
    applied_rows = []
    for question in tagged_questions:
        question_id = question.get("question_id")
        suggestion = suggestions.get(question_id)
        if not suggestion or suggestion.get("action") != "change":
            continue

        before = dict(question.get("tags") or {})
        after = dict(suggestion.get("suggested_tags") or {})
        if not after:
            continue

        after["tags_reviewed"] = False
        after["tags_generated_by"] = _calibrated_generator_name(before.get("tags_generated_by", "local_rules_v1"))
        question["tags"] = after
        applied_rows.append(
            {
                "question_id": question_id,
                "changed_fields": suggestion.get("changed_fields", []),
                "before_primary_knowledge": before.get("primary_knowledge", ""),
                "after_primary_knowledge": after.get("primary_knowledge", ""),
                "before_secondary_knowledge": before.get("secondary_knowledge", []),
                "after_secondary_knowledge": after.get("secondary_knowledge", []),
                "before_ability_tags": before.get("ability_tags", []),
                "after_ability_tags": after.get("ability_tags", []),
                "calibration_rationale": suggestion.get("calibration_rationale", ""),
                "needs_teacher_review": True,
            }
        )
    return applied_rows


def _calibrated_generator_name(current):
    marker = "agent_model_calibration_v1"
    if marker in current:
        return current
    return f"{current}+{marker}" if current else marker


def _write_change_report(path, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "question_id",
        "changed_fields",
        "before_primary_knowledge",
        "after_primary_knowledge",
        "before_secondary_knowledge",
        "after_secondary_knowledge",
        "before_ability_tags",
        "after_ability_tags",
        "calibration_rationale",
        "needs_teacher_review",
    ]
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            csv_row = dict(row)
            for key in ("changed_fields", "before_secondary_knowledge", "after_secondary_knowledge", "before_ability_tags", "after_ability_tags"):
                csv_row[key] = "；".join(csv_row.get(key) or [])
            writer.writerow(csv_row)


def _summary(tagged_questions, suggestions, applied_rows, output, tags_path, suggestions_path):
    generated_by_counts = Counter((item.get("tags") or {}).get("tags_generated_by", "") for item in tagged_questions)
    primary_counts = Counter((item.get("tags") or {}).get("primary_knowledge", "") for item in tagged_questions)
    return {
        "source_tags": str(tags_path),
        "suggestions": str(suggestions_path),
        "output_dir": str(output),
        "question_count": len(tagged_questions),
        "suggestion_count": len(suggestions),
        "applied_changes": len(applied_rows),
        "teacher_reviewed_true": sum(1 for item in tagged_questions if (item.get("tags") or {}).get("tags_reviewed") is True),
        "generated_by_counts": dict(generated_by_counts),
        "top_primary_knowledge": dict(primary_counts.most_common(10)),
        "calibrated_tags": str(output / "tags" / "all_question_tags.calibrated.json"),
        "change_report": str(output / "calibration_change_report.csv"),
        "student_mastery": (
            str(output / "student" / "student_mastery.jsonl")
            if (output / "student" / "student_mastery.jsonl").exists()
            else None
        ),
    }


def _summary_markdown(summary):
    lines = [
        "# Applied Model Calibrations",
        "",
        f"- Source tags: `{summary['source_tags']}`",
        f"- Suggestions: `{summary['suggestions']}`",
        f"- Questions: {summary['question_count']}",
        f"- Suggestion records: {summary['suggestion_count']}",
        f"- Applied changes: {summary['applied_changes']}",
        f"- Teacher-reviewed tags: {summary['teacher_reviewed_true']}",
        "",
        "## Generated By",
        "",
    ]
    for key, value in summary["generated_by_counts"].items():
        lines.append(f"- {key}: {value}")
    lines.extend(["", "## Top Primary Knowledge", ""])
    for key, value in summary["top_primary_knowledge"].items():
        lines.append(f"- {key}: {value}")
    lines.extend(
        [
            "",
            "## Files",
            "",
            f"- Calibrated tags: `{summary['calibrated_tags']}`",
            f"- Change report: `{summary['change_report']}`",
        ]
    )
    if summary["student_mastery"]:
        lines.append(f"- Student mastery: `{summary['student_mastery']}`")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    main()
